### ISSUE TITLE
Error downloading files

### ISSUE THREAD

**Issue by aharris88** [BibleJS/BibleApp#14]
When I run a command like `bible 'Genesis 1:1'`, I get this error:

```
info  ~/.bible directory was not found. Downloading packages. This may take a while.
/usr/local/lib/node_modules/bible/bin/bible:189
    if (err) { throw err; }
                     ^
Error: Command failed: /bin/sh -c npm install
installation/preinstall.sh: line 7: wget: command not found
installation/preinstall.sh: line 11: wget: command not found

npm ERR! Darwin 14.3.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.1
npm ERR! npm  v2.7.3
npm ERR! code ELIFECYCLE
npm ERR! bible-romanian@0.1.0 preinstall: `installation/preinstall.sh`
npm ERR! Exit status 127
npm ERR!
npm ERR! Failed at the bible-romanian@0.1.0 preinstall script 'installation/preinstall.sh'.
npm ERR! This is most likely a problem with the bible-romanian package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     installation/preinstall.sh
npm ERR! You can get their info via:
npm ERR!     npm owner ls bible-romanian
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/adamharris/.bible/ro/npm-debug.log

    at ChildProcess.exithandler (child_process.js:744:12)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1008:16)
    at Socket.<anonymous> (child_process.js:1176:11)
    at Socket.emit (events.js:107:17)
    at Pipe.close (net.js:476:12)
```

**Comment by aharris88** [comment]
I think it's because I'm on a mac, so I don't have wget available.

**Comment by IonicaBizau** [comment]
If you're not using the Romanian version, just remove it from config (`~/.bible-config.json`). I hope that helps. Indeed it's an issue.

**Comment by aharris88** [comment]
Ah, yes, that works.

**Comment by IonicaBizau** [comment]
> `installation/preinstall.sh: line 7: wget: command not found`

It's saying you need `wget`. I opened this issue in the bible-romanian package: https://github.com/BibleJS/bible-romanian/issues/1

Thanks for report! :apple:

**Comment by IonicaBizau** [comment]
:ship: `2.0.1` :tada: 

Tested on my Raspberry Pi too! It's working. Thanks! :smile:

**Comment by dawsonpaul** [comment]
I tried to remove the Romanian language and I still get

    $ bible 'Genesis 1:1'
    warn  Cannot read the configuration file. Reason: undefined
    /usr/local/lib/node_modules/bible/bin/bible:72
    language = language || config.language;
                             ^

    TypeError: Cannot read property 'language' of null
    at Object.<anonymous> (/usr/local/lib/node_modules/bible/bin/bible:72:30)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Function.Module.runMain (module.js:575:10)
    at startup (node.js:160:18)
    at node.js:456:3

**Comment by IonicaBizau** [comment]
@dawsonpaul Can you post the content of `~/.bible-config.json`?

**Comment by dawsonpaul** [comment]
{
  "versions": {
    "en": {
      "source": "https://github.com/BibleJS/bible-english",
      "version": "master",
      "language": "en"
    },
  "resultColor": "255, 0, 0",
  "language": "en",
  "searchLimit": 10
}

**Comment by IonicaBizau** [comment]
@dawsonpaul There is a missing `}`:

```json
{
	"versions": {
		"en": {
			"source": "https://github.com/BibleJS/bible-english",
			"version": "master",
			"language": "en"
		}
	},
	"resultColor": "255, 0, 0",
	"language": "en",
	"searchLimit": 10
}
```

**Comment by dawsonpaul** [comment]
Thank you. I am still having an issue

$ bible --lang en 'John 1:1-10' 'Genesis 2:3-7'
module.js:442
    throw err;
    ^

Error: Cannot find module 'request'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/pauldawson/.bible/en/index.js:2:15)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)

**Comment by IonicaBizau** [comment]
@dawsonpaul See #19. Or follow https://github.com/BibleJS/BibleApp/issues/18#issuecomment-172739460 directly.
