### ISSUE TITLE
Getting Error: Cannot find module 'qs'

### ISSUE THREAD

**Issue by Anebimeta4** [BibleJS/BibleApp#18]
# Hi, this is a splendid project!
Unfortunately,  I have not been able to make it work yet.
I keep getting the error msg, 
``` js
Error : Cannot find module 'qs'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/a.agbo/.bible/en/node_modules/request/request.js:8:10)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
```

**Comment by IonicaBizau** [comment]
@Anebimeta4 Thank you! :joy: 

Looks like the `request` module failed to be installed.
Do an `npm install` manually, like below:

```sh
cd /Users/a.agbo/.bible/en
rm -rf node_modules
npm i
```

Hopefully it will fix the problem. :smile:

**Comment by Anebimeta4** [comment]
@IonicaBizau Thanks :+1: 
That fixed it.

**Comment by IonicaBizau** [comment]
Great! :+1:

**Comment by dawsonpaul** [comment]
I'm on OSX which could be the issue

Pauls-MBP:en pauldawson$ npm install 
npm WARN deprecated user-agent-parser@0.6.0: use ua-parser-js instead
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm ERR! Darwin 15.3.0
npm ERR! argv "/usr/local/Cellar/node/6.2.1/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v6.2.1
npm ERR! npm  v3.9.3
npm ERR! code EREADFILE

npm ERR! Error extracting /Users/pauldawson/.npm/ansi-codes/0.0.0/package.tgz archive: ENOENT: no such file or directory, open '/Users/pauldawson/.npm/ansi-codes/0.0.0/package.tgz'
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/pauldawson/.bible/en/npm-debug.log

**Comment by IonicaBizau** [comment]
@dawsonpaul This looks like a `npm` issue. Just delete your npm cache and try again: `rm ~/.npm`.

**Comment by dawsonpaul** [comment]
FYI - I fixed it by doing the following

cd .npm/ansi-codes/
mv 2.0.0/ 0.0.0

cd /Users/p<homedir>/.npm/new-format/
mv 0.0.1/ 0.0.0
