### ISSUE TITLE
Cannot find module 'request' ?

### ISSUE THREAD

**Issue by slmjkdbtl** [BibleJS/BibleApp#19]
``` bash
$ bible 'Genesis 1:1'
```

``` bash
module.js:341
    throw err;
    ^

Error: Cannot find module 'request'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/Users/Voyga/.bible/en/index.js:2:15)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
```

node version => `v5.5.0`
npm version => `v3.5.3`

**Comment by IonicaBizau** [comment]
@Voyga Whoups, looks like there is an issue when `npm install`ing the dependencies. Check out the workaround here: https://github.com/BibleJS/BibleApp/issues/18#issuecomment-172739460

**Comment by Voyga** [comment]
@IonicaBizau I solved it after running `npm install` in `~/.bible/en`. And now I'm running into #17 issue...

**Comment by IonicaBizau** [comment]
@Voyga Hmm, what's the output of the following command (you have to have `curl` installed, otherwise just open the [link](http://labs.bible.org/api/?type=json&passage=Genesis%201:29) in the browser)?

```sh
curl http://labs.bible.org/api/?type=json&passage=Genesis%201:29
```

**Comment by Voyga** [comment]
@IonicaBizau I think its just because of my unstable internet. `curl` went fine and now the `babel` command works just fine. Thanks!

**Comment by IonicaBizau** [comment]
@Voyga Yeah, somewhere the error is not handled correctly. Basically, if the request fails (e.g. no internet), the app will just crash.

**Comment by teddyaryono** [comment]
Hi, sorry for bringing up the issue. I was landed on the same issue, and I solved it by manually installing the `request` module.

`cd $HOME/.bible/en`
`npm install --save request`

**Comment by IonicaBizau** [comment]
@teddyaryono Thanks for that. I have on my list to update this module soon. 🚀

**Comment by IonicaBizau** [comment]
This should be fixed now.
