### ISSUE TITLE
[EXPIRED] Windows standalone binary

### ISSUE THREAD

**Issue by sergeevabc** [BibleJS/BibleApp#21]
Dear team behind BibleApp,
Could you be so kind to generate ```.exe``` for the rest of us who use Windows w/o Node?
I’m told that either [Nexe][1] or [EnclosureJS][2] might help you to achieve that.

[1]: https://www.npmjs.com/package/nexe
[2]: http://enclosejs.com/

**Comment by sergeevabc** [comment]
Err… Hello?

**Comment by IonicaBizau** [comment]
I'm planning a new major version of this app and will hopefully get this fixed too. Stay tuned!

**Comment by sergeevabc** [comment]
Six months passed. Err… Hello?

**Comment by sergeevabc** [comment]
@IonicaBizau, did you get a chance to look into this more thoroughly?

**Comment by IonicaBizau** [comment]
@sergeevabc I've been busy with other projects. Will take care of this, but I don't have an ETA...
