### ISSUE TITLE
[search] broken with --lang en

### ISSUE THREAD

**Issue by DoubleU23** [BibleJS/BibleApp#22]
can't search in english, although i have english installed

`bible --lang ro --search 'Meroza' --onlyVerses`
=> Blestemaţi pe Meroza, a zis Îngerul Domnului, blestemaţi, blestemaţi pe locuitorii lui; căci n-au venit în ajutorul Domnului, în ajutorul Domnului, printre oamenii viteji.

`bible --lang en --search 'jesus'`
Results for search: jesus
**Error:  Module don't support search method**

`bible --lang en --onlyVerses 'John 1:1-10' 'Genesis 2:3-7'`
God blessed the seventh day and made it holy because on it he ceased all the work that he had been doing in creation.
This is the account of the heavens and the earth when they were created ... ... ...

**Comment by IonicaBizau** [comment]
Well, the error is pretty clear: searching is simply not available for the English version yet.

**Comment by DoubleU23** [comment]
i was confused by the error, because i don't understand how a search-feature depends on the language im using (isn't it the same feature-function, applied on another source)
maybe you're using a different API target for english, that would explain why

also i didn't found the search function in the code... so i don't know if i could help "fixing" this

i don't wanted to bother you, just wanted to get clear on this error

**Comment by IonicaBizau** [comment]
Each language package implements its own searching method.

For instance, the English version uses an [request-based workflow](https://github.com/BibleJS/bible-english/blob/3dd288a3f2b63c2bb22836104ad33204fa9b9ef5/index.js#L26-L29), which also means you should be connected to the internet.

The Romanian one downloads the JSON files locally.


I'm not sure if this API service supports searching. From a quick look, it doesn't seem to: http://labs.bible.org/api_web_service

And as long the API service doesn't have support for searching, we cannot do anything else than switching to a different API service, probably.
