### ISSUE TITLE
Random Article from bible

### ISSUE THREAD

**Issue by BogBel** [BibleJS/BibleApp#23]
Hey, i'd like to use this with cowsay instead of single fortune, but i need a way to get a random article instead of predefined one.
I think i can do it with myself, does anybody else need this?

**Comment by IonicaBizau** [comment]
You could simply generate a random reference and pass it to `bible`. I'm not sure if that's what you want.

**Comment by BogBel** [comment]
I am looking for smthng like 

> bible --lang en --rand --onlyVerses

To pass it to cowsay. I think this should be implemented inside module.

**Comment by rgamec** [comment]
> I am looking for smthng like
> 
> > bible --lang en --rand --onlyVerses
> 
> To pass it to cowsay. I think this should be implemented inside module.

An alternative method could be to just call the http://labs.bible.org/api/?passage=random API endpoint, something like this will work:
`wget -q -O - "http://labs.bible.org/api/?passage=random" | sed -e 's/<[^>]*>//g' | cowsay`

I agree this would be a fun feature to add into BibleApp.
