### ISSUE TITLE
Ubuntu 18.04 NPM@3.5.2

### ISSUE THREAD

**Issue by nickajshelden** [BibleJS/BibleApp#28]
npm i -g bible throws SEVERAL(didn't paste them all) errors like:

`npm ERR! Error: EACCES: permission denied, access '/usr/local/lib/node_modules/bible'
npm ERR!  { Error: EACCES: permission denied, access '/usr/local/lib/node_modules/bible'
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/usr/local/lib/node_modules/bible' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.
npm ERR! Linux 4.15.0-96-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "i" "-g" "bible"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! path npm-debug.log.2784587636
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall open
`
taking the suggestion to run as admin (sudo npm i -g bible) seems to work, but throws this too:
`npm WARN In bible@2.0.1 replacing bundled version of bible.js with bible.js@3.0.0
`
running "bible" then spits out the help message, good.
running "bible 'Genesis 1:1'" as suggested by the help message gives me this:
`/usr/local/lib/node_modules/bible/bin/bible:189
    if (err) { throw err; }
               ^

Error: spawn git ENOENT
    at _errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:695:11)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3`

any ideas?
and sorry for formatting, github wasn't playing nice today either. 
no log file was locatable, but I can try to generate one if needed.

**Comment by IonicaBizau** [comment]
This is strongly related to how you configure npm locally. Don't install packages via sudo. It is not a good practice.
